version: "3.8"

services:
  gateway:
    build: .
    ports:
      - "8000:8000"
    environment:
      - AUTH_SERVICE_URL=http://auth-service:8001
      - JOB_SERVICE_URL=http://job-service:8002
      - NOTIFICATION_SERVICE_URL=http://notification-service:8003
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
      - auth-service
    volumes:
      - .:/app
    networks:
      - microservices-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - microservices-network

  auth-service:
    build: ../auth-service
    ports:
      - "8001:8000"
    networks:
      - microservices-network

networks:
  microservices-network:
    driver: bridge
